---
# geerlingguy.firewall
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
firewall_additional_rules:
  # dummy rules
  - "iptables -A INPUT -p tcp --dport 6379 -s 1.1.1.1 -j ACCEPT" # US
  - "iptables -A INPUT -p tcp --dport 6379 -s 4.4.4.4 -j ACCEPT" # EU
  - "iptables -A INPUT -p tcp --dport 6379 -s 8.8.8.8 -j ACCEPT" # ASIA

# geerlingguy.php
php_enable_php_fpm: true
php_webserver_daemon: nginx
php_packages_extra:
  - php7.1-mysql
  - php7.1-mcrypt

# geerlingguy.certbot
certbot_create_if_missing: yes
certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
certbot_auto_renew_options: "--no-self-upgrade"
certbot_admin_email: example@gmail.com
certbot_certs:
  - domains:
      - www.malprave.corp
      - malprave.corp

# geerlingguy.nginx
nginx_extra_http_options: |
    gzip on;
    gzip_proxied any;
    gzip_static on;
    gzip_http_version 1.0;
    gzip_disable "MSIE [1-6]\.";
    gzip_vary on;
    gzip_comp_level 4;
    gzip_types
        text/plain
        text/css
        text/xml
        text/javascript
        application/javascript
        application/x-javascript
        application/json
        application/xml
        application/xml+rss
        application/xhtml+xml
        application/x-font-ttf
        application/x-font-opentype
        image/svg+xml
        image/x-icon;
    gzip_buffers 16 8k;
    gzip_min_length 2048;

nginx_remove_default_vhost: true
nginx_server_tokens: "off"
# yamllint disable-line rule:line-length
ssl_ciphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AE128-SHA256"

# modern profile from
# mozilla.github.io/server-side-tls/ssl-config-generator/
ssl_config: |
      ssl_certificate      /etc/letsencrypt/live/malprave.corp/fullchain.pem;
      ssl_certificate_key  /etc/letsencrypt/live/malprave.corp/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/malprave.corp/chain.pem;
      ssl_dhparam          /etc/ssl/dhparam.pem;

      # Sessions
      ssl_session_timeout 1d;
      ssl_session_cache shared:SSL:50m;
      ssl_session_tickets off;

      # Protocol/Cipher list
      ssl_protocols TLSv1.2;
      ssl_ciphers '{{ ssl_ciphers }}';
      ssl_prefer_server_ciphers on;

      # Buffer
      ssl_buffer_size 8k;

      # HSTS
      add_header Strict-Transport-Security max-age=15768000;

      # OSCP
      ssl_stapling on;
      ssl_stapling_verify on;

      resolver 8.8.8.8 8.8.4.4 valid=300s;
      resolver_timeout 5s;

nginx_static_list: "jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc"

nginx_vhosts:

  - listen: "80"
    server_name: "www.malprave.corp malprave.corp"
    return: "301 https://$host$request_uri"
    filename: "force_https.conf"

  - listen: "443 ssl http2"
    server_name: "www.malprave.corp malprave.corp"
    server_name_redirect: "malprave.corp"
    root: "/var/www/malprave/current/public"
    index: "index.php index.html"
    access_log: "/var/log/nginx/malprave.access.log"
    error_log: "/var/log/nginx/malprave.error.log"
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "malprave.conf"
    extra_parameters: |
      add_header X-Frame-Options "SAMEORIGIN";
      add_header X-XSS-Protection "1; mode=block";
      add_header X-Content-Type-Options "nosniff";

      location / {
          try_files $uri $uri/ /index.php?$query_string;
      }

      location /kookaburra/ {
          proxy_pass http://127.0.0.1:8000;
      }

      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
          fastcgi_hide_header X-Powered-By;
      }

      # Media: images, icons, video, audio, HTC
      location ~* \.(?:{{ nginx_static_list }})$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
      }

      # CSS and Javascript
      location ~* \.(?:css|js)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
      }

      error_page 404 /index.php;

      {{ ssl_config }}
