---
dist: xenial
cache:
 pip: true
 directories:
  - ~/.ansible/roles

before_script:
 - sudo apt-get update -q
 - sudo apt-get install -q python-pip
 - pip install --upgrade --user ansible-lint ansible yamllint
 - ansible --version
 - ansible-lint --version
 - ansible-galaxy install -r .requirements.yml

jobs:
 include:

  - name: YAML Lint
    script: yamllint .

  - name: Ansible Lint
    script: ansible-lint *.yml

  - name: Ansible Syntax Check
    script: ansible-playbook --inventory inventory --syntax-check *.yml
