---
dist: xenial

before_script:
  - sudo apt-get update -q
  - sudo apt-get install -q  yamllint ansible-lint ansible
  - ansible --version
  - ansible-lint --version

jobs:
  include:
    - stage: lint / syntax check
      script: yamllint .
      script: ansible-lint *.yml
      script: ansible-playbook --inventory inventory --syntax-check *.yml

